### Variables
@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGRlYzQ1MzBmMDYzZDFjYTkwNDQyNTUiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTk0Mjk5MjQsImV4cCI6MTc2MDAzNDcyNH0.x2uxXhWSJd_MePkqNCAidRC-qqzo8lvwywS1obQFeV8

### Health Check
GET {{baseUrl}}

### Register User
# @name register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "max@example.com",
  "password": "strongPassword123",
  "fullName": "Max Amini"
}

### Login
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "max@example.com",
  "password": "strongPassword123"
}

### Get Current User
GET {{baseUrl}}/api/auth/me
Authorization: Bearer {{login.response.body.data.token}}
